# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  prosperitopiawebapi:
    image: prosperitopia-server
    build:
      context: .
      dockerfile: Prosperitopia.Web.Api/Dockerfile
    ports:
      - 7117:7117
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
